import { showTime } from "./time.js";
import { getLocalStorage, setLocalStorage } from "./localStorage.js";
import { setBg, getSlideNext, getSlidePrev } from "./slider.js";
import { getWeather, setCity, city } from "./weather.js";
import { getQuotes, changeQuote } from "./quote.js";
import { playAudio, play, playPrev, playNext } from "./audio.js";
import { playList } from "./playList.js";

showTime();
getQuotes();
setBg();
getWeather();
console.log(playList);
window.addEventListener("load", getLocalStorage);
window.addEventListener("beforeunload", setLocalStorage);
document.querySelector(".slide-prev").addEventListener("click", getSlidePrev);
document.querySelector(".slide-next").addEventListener("click", getSlideNext);
document.addEventListener("DOMContentLoaded", getWeather);
city.addEventListener("keypress", setCity);
changeQuote.addEventListener("click", getQuotes);
play.addEventListener("click", playAudio);
document.querySelector(".play-prev").addEventListener("click", playPrev);
document.querySelector(".play-next").addEventListener("click", playNext);
